# -*- coding: utf-8 -*-
"""Cálculo de Métricas de Avaliação de Aprendizado .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBEsb5vGRJTthcTanh4THRyLDODJilGD
"""

# Valores arbitrários
VP = 50  # Verdadeiros Positivos
VN = 40  # Verdadeiros Negativos
FP = 10  # Falsos Positivos
FN = 5   # Falsos Negativos

# Acurácia
acuracia = (VP + VN) / (VP + VN + FP + FN)

# Sensibilidade (Recall)
sensibilidade = VP / (VP + FN)

# Especificidade
especificidade = VN / (VN + FP)

# Precisão
precisao = VP / (VP + FP)

# F-score (F1)
f1_score = 2 * (precisao * sensibilidade) / (precisao + sensibilidade)

print(f"Acurácia: {acuracia:.2f}")
print(f"Sensibilidade (Recall): {sensibilidade:.2f}")
print(f"Especificidade: {especificidade:.2f}")
print(f"Precisão: {precisao:.2f}")
print(f"F1-Score: {f1_score:.2f}")

Acurácia: 0.90
Sensibilidade (Recall): 0.91
Especificidade: 0.80
Precisão: 0.83
F1-Score: 0.87